[workspace]
edition = "2021"
resolver = "2"
members = [
  "imessage-database",
  "imessage-exporter",
]
imessage-database = "1.4.0"

[profile.release]
# Perform Link Time Optimization
lto = true
# Do not unwind stack on crash
panic = "abort"
